# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "bento/amazonlinux-2"
SLAVE_COUNT = 2

Vagrant.configure("2") do |config|

  config.vm.box = BOX_IMAGE
  config.vm.hostname = "config"
  config.vm.network :private_network, ip: "10.0.0.10"
  # If "synced_folder" is enabled, the owner of vagrant becomes
  # owner of /data/db and mongod is not able to write a lock
  # file in this directory
  # config.vm.synced_folder "data", "/data"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end
  # Files to /etc or /lib cannot be directly copied
  # So we do it to a temporary location and move it 
  # from there
  # Reference: https://stackoverflow.com/a/54099162/5305151
  config.vm.provision "file", source: "mongodb-conf/mongod.service", destination: "/tmp/mongod.service"
  config.vm.provision "file", source: "mongodb-conf/mongod.conf", destination: "/tmp/mongod.conf"
  config.vm.provision "shell", path: "./automate/init.sh"
  config.vm.provision "shell", path: "./automate/install.sh"

end
